### ISSUE TITLE
Using metall with STL container

### ISSUE THREAD

**Issue by LukasKerk** [LLNL/metall#130]
I followed your (really good) example folder to get a feeling for the library. Everything went well while using boost container or std::vector. However with std::string I wasn't so lucky.
```c++
using persistent_string =
  std::basic_string<char, std::char_traits<char>,
    metall::manager::allocator_type<char>>;
int main() {
    metall::manager manager(metall::create_only, "/tmp/datastore");
    auto str = manager.construct<persistent_string>("mystring")(
        "Hello, World!", manager.get_allocator<>());
    std::cout << *str << '\n';
}
```
Do I need to do something different or are some STL container simply not supported?

**Comment by KIwabuchi** [comment]
Hi @LukasKerk ,

Thank you for playing with the examples.

Unfortunately, most of the containers that come with GCC are not compatible with Metall.

They ignore the pointer type in the allocator (i.e., `metall::manager::allocator_type`) and assumes that only raw pointers (C style pointers) are used.
On the other hand, one has to use [offset pointer](https://www.boost.org/doc/libs/1_75_0/doc/html/interprocess/offset_ptr.html) instead of the raw pointer to store pointers/containers into persistent memory using Metall.

As you found, Boost.Container library is fully compatible with Metall.
Also, you may be able to use the containers in Clang (just use clang++ instead of g++).

Keita

**Comment by LukasKerk** [comment]
Hi @KIwabuchi ,
thank you for your fast and detailed answer. 
I tried to compile it both with gcc-10 and clang-10, both generate more or less the same errors.
So it seems like I will simply switch to boost where I can.
